name: Ping Schedule Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          date
          echo "Ping schedule test berhasil jalan"
